# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# NS ENV settings
title: Legendary Arena
email: developer@larena.bow
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aohycent.github.io" # the base hostname & protocol for your site
github_username:  aohycent

# Build settings
markdown: kramdown
